<?php


namespace App\Nkid\ModelLogic\Wheel;


use App\Nkid\ModelLogic\BaseModelLogic;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

class LogModelLogic extends BaseModelLogic{


	public function getCollection(Request $request): AnonymousResourceCollection {
		parent::getCollection($request); // TODO: Change the autogenerated stub
	}

	public function index(Request $request): AnonymousResourceCollection {
		parent::index($request); // TODO: Change the autogenerated stub
	}

	public function store(Request $request): JsonResponse {
		parent::store($request); // TODO: Change the autogenerated stub
	}

	public function update($id, Request $request): JsonResponse {
		parent::update($id, $request); // TODO: Change the autogenerated stub
	}

	public function destroy($ids): JsonResponse {
		parent::destroy($ids); // TODO: Change the autogenerated stub
	}

}
